apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: network-exporter
  labels:
    app: network-exporter
spec:
  selector:
    matchLabels:
      app: network-exporter
  template:
    metadata:
      labels:
        app: network-exporter
    spec:
      hostNetwork: true
      hostPID: true
      containers:
        - name: exporter
          image: network-exporter-ebpf:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080
              name: metrics

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi

          readinessProbe:
            httpGet:
              path: /metrics
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /metrics
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20

          securityContext:
            privileged: true